version: '3'

services:
  nextjs:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      NODE_ENV: development
      HOST: 0.0.0.0
    command: npm run dev
    networks:
      - universal-books  # Attach to the shared network

volumes:
  node_modules:  # Declare the node_modules volume
    driver: local


networks:
  universal-books:
    external: true  # Use the external network
